import { resolve } from 'node:path';
import { BUILT_IN_RULES } from '../rules/index.js';
import { defaultFS } from '../infrastructure/fs.js';

export interface InitOptions {
  configPath?: string;
  cwd?: string;
}

const RULE_DESCRIPTIONS: Record<string, string> = {
  'no-hard-wait': 'Disallows waitForTimeout() — use web-first waiting instead',
  'deep-locator': 'Warns when CSS/XPath selector depth exceeds threshold',
  'unawaited-action': 'Flags async Playwright methods called without await',
  'zombie-locator': 'Flags Page Object properties never used in specs',
  'web-first-assertion': 'Flags non-web-first assertions (e.g. isVisible().toBe(true))',
  'leaky-page-object': 'Warns when specs access the page object directly',
  'no-page-pause': 'Disallows page.pause() debugging calls',
  'no-focused-test': 'Disallows test.only() / describe.only()',
  'no-hardcoded-base-url': 'Disallows hardcoded HTTP/HTTPS URLs in page.goto()',
  'no-hardcoded-timeout': 'Disallows magic number timeout values',
  'no-console-in-test': 'Disallows console.* calls in spec files',
  'no-skipped-test': 'Flags test.skip() calls',
};

function buildConfigTemplate(): string {
  const ruleLines = BUILT_IN_RULES.map((rule) => {
    const desc = RULE_DESCRIPTIONS[rule.id] ?? rule.description;
    const category = rule.category ?? 'uncategorized';
    const defaultEntry = rule.id === 'deep-locator'
      ? `["${rule.defaultSeverity}", { "maxDepth": 3 }]`
      : `"${rule.defaultSeverity}"`;
    return [
      `    // ${rule.id} [${category}]: ${desc}`,
      `    "${rule.id}": ${defaultEntry}`,
    ].join('\n');
  }).join(',\n');

  return `{
  // pw-eslint configuration
  // Generated by: pw-eslint --init
  // Docs: github.com/playwright-audit/pw-eslint
  // Files to include in analysis
  "include": ["**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js"],

  // Files to exclude from analysis
  "exclude": ["node_modules"],

  // Glob pattern to identify Page Object files (used by leaky-page-object, zombie-locator)
  "pageObjectPattern": "pages/**/*.ts",

  // Glob pattern to identify spec files (used by leaky-page-object)
  "specPattern": "**/*.spec.ts",

  // Optionally restrict analysis to specific rule categories.
  // Categories: "flakiness" | "hygiene" | "style" | "correctness"
  // Leave empty [] to run all rules.
  // "categoryFilter": ["flakiness", "hygiene"],

  // Rule configuration: severity ("error" | "warn" | "off") or ["severity", { options }]
  "rules": {
${ruleLines}
  }

  // Per-directory overrides example (uncomment and adapt):
  // "overrides": [
  //   {
  //     "files": ["tests/legacy/**"],
  //     "rules": {
  //       "no-hard-wait": "warn"
  //     }
  //   }
  // ]
}
`;
}

export function runInit(options: InitOptions = {}): void {
  const cwd = options.cwd ?? process.cwd();
  const fs = defaultFS;
  const targetPath = options.configPath
    ? resolve(options.configPath)
    : resolve(cwd, '.pw-eslintrc.json');

  if (fs.exists(targetPath)) {
    process.stderr.write(
      `[pw-eslint] Config already exists at "${targetPath}". No changes made.\n`,
    );
    process.exit(0);
  }

  try {
    fs.writeFile(targetPath, buildConfigTemplate());
  } catch (err) {
    process.stderr.write(
      `[pw-eslint] Failed to write config to "${targetPath}": ${err instanceof Error ? err.message : String(err)}\n`,
    );
    process.exit(2);
    return;
  }

  process.stdout.write(`[pw-eslint] Config written to "${targetPath}"\n`);
  process.exit(0);
}
